version: '3'

services:

  nginx:
    image: nginx:1.25.4
    container_name: itgov_contracts_nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - itgov_contracts_network

  backend:
    image: ghcr.io/gavillar/itgov-contracts-maven:v0.0.41
    container_name: itgov_contracts_backend
    hostname: itgov_contracts
    restart: always
    networks:
      - itgov_contracts_network
    ports:
      - "9632"

networks:
  itgov_contracts_network:
    driver: bridge
